export {
  CPROTOCOL,
  CVERSION,
  EAssetKind,
  ESliceType,
  EEvidenceSource,
  EScriptRole,
  ETrackKind,
  ETrackRole,
  ETransitionType,
  ECaptureTimeSource,
  EMediaRootCategory,
  ICaptureTime,
  IMediaRoot,
  IKtepEvidence,
  IKtepAsset,
  IKtepSlice,
  IKtepScriptAction,
  IKtepScriptSelection,
  IKtepScriptBeat,
  IKtepScript,
  IKtepKenBurns,
  IKtepTransform,
  IKtepTransition,
  IKtepTrack,
  IKtepClip,
  IKtepTimeline,
  IKtepSubtitle,
  IKtepProject,
  IKtepDoc,
  IStyleNarrative,
  IStyleVoice,
  IStyleSection,
  IStyleProfile,
  IStyleCatalogEntry,
  IStyleCatalog,
  IStoreManifest,
  EClipType,
  ESamplingProfile,
  EVlmMode,
  ETargetBudget,
  EFineScanMode,
  IInterestingWindow,
  IMediaAnalysisPlan,
  ICoarseSample,
  ITranscriptSegment,
  EEmbeddedGpsOriginType,
  IEmbeddedGpsPoint,
  IEmbeddedGpsBinding,
  IInferredGps,
  IAssetCoarseReport,
  IChronologyCorrection,
  IMediaChronology,
  IDeviceMediaRootPath,
  IDeviceMediaProjectMap,
  IDeviceMediaMapFile,
} from './schema.js';

export {
  validateKtepDoc,
  type IValidationError,
  type IValidationResult,
} from './validator.js';
