export {
  ResolveVolcVoiceoverError,
  VolcTtsHttpClient,
  buildResolveVolcVoiceoverConfigSummaryTsv,
  errorToTsv,
  ensureResolveVolcVoiceoverIpcDirs,
  findKairosProjectForResolve,
  formatResolveVolcVoiceoverSynthesizeTsv,
  mergeSelectedSubtitlesForSynthesis,
  parseTtsResponse,
  processResolveVolcVoiceoverIpcOnce,
  requestHash,
  resolveProjectVoiceoverMedia,
  resolveVolcVoiceoverIpcPaths,
  safeSegment,
  startResolveVolcVoiceoverIpcServer,
  stableHash,
  stripResolveProjectSuffix,
  synthesizeResolveVolcVoiceoverJob,
  synthesizeResolveVolcVoiceoverTsv,
  unitIdForSubtitle,
  type IResolveVoiceoverIpcPaths,
  type IResolveVoiceoverIpcServer,
  type IResolveVoiceoverJobInput,
  type IResolveVoiceoverProjectMatch,
  type IResolveVoiceoverSubtitleInput,
  type IResolveVoiceoverSynthesizeResult,
  type IResolveVoiceoverUnitManifest,
  type IVolcTtsClient,
  type IVolcTtsPublicSettings,
} from './resolve-volc-voiceover.js';
