#!/usr/bin/env bash
set -euo pipefail

ACTION="${1:-start}"
CATEGORY_SLUG="${KAIROS_SA_CATEGORY:-personal-serious-works}"
PORT="${KAIROS_SA_PORT:-8940}"
OPEN_BROWSER="${KAIROS_SA_OPEN:-true}"
TAIL_LINES="${KAIROS_SA_TAIL:-80}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
PROGRESS_DIR="$REPO_ROOT/.tmp/style-analysis/$CATEGORY_SLUG"
SERVER_KEY="style-analysis-progress-$CATEGORY_SLUG"

KAIROS_PROGRESS_DIR="$PROGRESS_DIR" \
KAIROS_PROGRESS_KEY="$SERVER_KEY" \
KAIROS_PROGRESS_PORT="$PORT" \
KAIROS_PROGRESS_OPEN="$OPEN_BROWSER" \
KAIROS_PROGRESS_TAIL="$TAIL_LINES" \
  "$SCRIPT_DIR/kairos-progress.sh" "$ACTION"
